obj-$(CONFIG_MONITOR_PID) += pidnetmonitor.o

pidnetmonitor-objs := syscalls_monitor.o task_monitor.o filter.o proc_monitor.o db_monitor.o pidmonitor.o multi_pid_repository.o debugfs_monitor.o inject_monitor.o
